apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: santa
          image: bicky77/project4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: my-ssvc
spec:
  selector:
    app: myapp
  ports:
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
      nodePort: 32000
