---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomeappdeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: welcomeapp
  template:
    metadata: 
      name: welcomeapppod
      labels:
        app: welcomeapp 
    spec:
      containers:
      - name: welcomeappcontainer
        image: bicky77/project4
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: welcomeappsvc
spec:
  type: NodePort
  selector:
    app: welcomeapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
